Adding service mocks and service unit tests
murat96k/kitaptar.kz pull request #4
Opened 2023-10-05 13:49 UTC by uristemov

Adding service mocks and service unit tests;
Deleting unused comments;
Correcting codes;

2023-10-08 11:13 UTC, murat96k requested changes

2023-10-08 11:13 UTC, murmurat commented on api/author.go
> +	Id          uuid.UUID `json:"author_id"`
Id is never used, we can delete this field

2023-10-08 11:13 UTC, murmurat commented on internal/handler/book.go
>  	ctx.JSON(http.StatusCreated, req)
I think there's no need to return the request in response

2023-10-08 11:13 UTC, murat96k commented on internal/handler/book.go
>  	ctx.JSON(http.StatusCreated, req)
Returning ID makes more sense (just for future). But for now we can return just empty 201 response

2023-10-08 11:13 UTC, murat96k commented on internal/handler/router.go
> +		user.GET("/data", h.getUser)
"/user/books" should be here i think

2023-10-10 07:22 UTC, uristemov commented
Fixed errors in service mocks and unit tests
Working on murat96k comments
correcting createUser() errors
regenerate mocks for new createEntity codes
adding sql transactions on create method (Begin, Rollback, Commit)

2023-10-10 07:28 UTC, murat96k approved these changes

2023-10-10 08:18 UTC, merged